name: CI

on:
  push:

jobs:
  generate:
    name: Generate project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          path: accelerator-ci
      - name: Checkout CLI
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: pivotal/acc-engine
          ssh-key: ${{ secrets.ACC_SSH }}
          path: acc-engine
      - name: Set up JDK
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1
        with:
          java-version: '11'
      - name: Install YTT
        run: |
          wget -O- https://carvel.dev/install.sh > install.sh
          sudo bash install.sh
          ytt version
      - name: Build CLI
        run: |
          cd acc-engine/cli
          ./build.sh
      - name: Register Accelerator
        run: |
          cd acc-engine/cli
          java -jar target/cli-1.3.0-SNAPSHOT-exec.jar register hello-spring --from-location file://$GITHUB_WORKSPACE/accelerator-ci
      - name: Generate
        run: |
          cd acc-engine/cli
          java -jar target/cli-1.3.0-SNAPSHOT-exec.jar run --values ../../accelerator-ci/accelerator-test/values.json --output ../../generated-project hello-spring
      - name: Upload Generated Project
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: generated-project
          path: generated-project
  test-compile:
    name: Test Compile
    needs: [ generate ]
    runs-on: ubuntu-latest
    steps:
      - name: Download generated project
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: generated-project
      - name: Compile
        run: |
          chmod +x gradlew
          ./gradlew compileJava
  run-tests:
    name: Run Tests
    needs: [ generate ]
    runs-on: ubuntu-latest
    steps:
      - name: Download generated project
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: generated-project
      - name: Test
        run: |
          chmod +x gradlew
          ./gradlew test
  vulnerability-scan:
    name: Vulnerability Scan
    needs: [ generate ]
    runs-on: ubuntu-latest
    steps:
      - name: Download generated project
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: generated-project
      - name: Get grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: Scan
        run: |
          grype build/libs/test123-0.0.1-SNAPSHOT.jar
